#! /bin/sh

# https://developers.eveonline.com/resource/resources

# Carnyx 1.0 release
wget -c http://content.eveonline.com/data/Carnyx_1.0_Icons.zip
wget -c http://content.eveonline.com/data/Carnyx_1.0_Renders.zip
wget -c http://content.eveonline.com/data/Carnyx_1.0_Types.zip
wget -c http://cdn1.eveonline.com/data/Carnyx_1.0_113321_db.zip

# Aegis 1.2 release
wget -c http://content.eveonline.com/data/Aegis_1.2_Icons.zip
wget -c http://content.eveonline.com/data/Aegis_1.2_Renders.zip
wget -c http://content.eveonline.com/data/Aegis_1.2_Types.zip
wget -c http://cdn1.eveonline.com/data/Aegis_1.2_114300_db.zip

# Vanguard 1.0 release
wget -c http://content.eveonline.com/data/Vanguard_1.0_Icons.zip
wget -c http://content.eveonline.com/data/Vanguard_1.0_Renders.zip
wget -c http://content.eveonline.com/data/Vanguard_1.0_Types.zip
wget -c http://cdn1.eveonline.com/data/Vanguard_1.0_114986_db.zip

# Parallax 1.0 release
wget -c http://content.eveonline.com/data/Parallax_1.0_Icons.zip
wget -c http://content.eveonline.com/data/Parallax_1.0_Renders.zip
wget -c http://content.eveonline.com/data/Parallax_1.0_Types.zip
wget -c http://cdn1.eveonline.com/data/Parallax_1.0_115480_db.zip

# Frostline 1.0 release
wget -c http://content.eveonline.com/data/Frostline_1.0_Icons.zip
wget -c http://content.eveonline.com/data/Frostline_1.0_Renders.zip
wget -c http://content.eveonline.com/data/Frostline_1.0_Types.zip
wget -c http://cdn1.eveonline.com/data/Frostline_1.0_116241.zip

# YC-118-1 1.0 release
wget -c http://content.eveonline.com/data/YC-118-1_1.0_Icons.zip
wget -c http://content.eveonline.com/data/YC-118-1_1.0_Renders.zip
wget -c http://content.eveonline.com/data/YC-118-1_1.0_Types.zip
wget -c http://cdn1.eveonline.com/data/YC-118-1_1.0_116645.zip

wget -c http://content.eveonline.com/data/EVE_14.02_1.0_Icons.zip
wget -c http://content.eveonline.com/data/EVE_14.02_1.0_Renders.zip
wget -c http://content.eveonline.com/data/EVE_14.02_1.0_Types.zip

wget -c http://cdn1.eveonline.com/data/YC-118-2_1.0_116998.zip

# YC-118-3 1.0 release
wget -c http://cdn1.eveonline.com/data/YC-118-3_1.0_116998.zip
wget -c http://content.eveonline.com/data/YC-118-3_1.0_Icons.zip
wget -c http://content.eveonline.com/data/YC-118-3_1.0_Renders.zip
wget -c http://content.eveonline.com/data/YC-118-3_1.0_Types.zip

# Citadel 1.1 release
wget -c http://content.eveonline.com/data/Citadel_1.1_Icons.zip
wget -c http://content.eveonline.com/data/Citadel_1.1_Renders.zip
wget -c http://content.eveonline.com/data/Citadel_1.1_Types.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160429-TRANQUILITY.zip
wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160429-TRANQUILITY-legacy.zip

# YC-118-6 1.1 release
wget -c http://content.eveonline.com/data/YC-118-6_1.1_Icons.zip
wget -c http://content.eveonline.com/data/YC-118-6_1.1_Renders.zip
wget -c http://content.eveonline.com/data/YC-118-6_1.1_Types.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160704-TRANQUILITY.zip
wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160704-TRANQUILITY-legacy.zip

# YC-118-7 1.0 release
wget -c http://content.eveonline.com/data/YC-118-7_1.0_Icons.zip
wget -c http://content.eveonline.com/data/YC-118-7_1.0_Renders.zip
wget -c http://content.eveonline.com/data/YC-118-7_1.0_Types.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160809-TRANQUILITY.zip
wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160809-TRANQUILITY-legacy.zip

# YC-118-8 1.0 release
wget -c http://content.eveonline.com/data/YC-118-8_1.0_Icons.zip
wget -c http://content.eveonline.com/data/YC-118-8_1.0_Renders.zip
wget -c http://content.eveonline.com/data/YC-118-8_1.0_Types.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160912-TRANQUILITY.zip
wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20160912-TRANQUILITY-legacy.zip

# YC-118-9 1.0 (current) release
wget -c http://content.eveonline.com/data/YC-118-9_1.0_Icons.zip
wget -c http://content.eveonline.com/data/YC-118-9_1.0_Renders.zip
wget -c http://content.eveonline.com/data/YC-118-9_1.0_Types.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20161011-TRANQUILITY.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20161019-TRANQUILITY.zip
wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20161019-TRANQUILITY-legacy.zip

wget -c https://cdn1.eveonline.com/data/sde/tranquility/sde-20161114-TRANQUILITY.zip
